output DP-1 mode 1920x1080@60Hz pos 0 0 transform 270
#output DP-1 bg ~/Pictures/lonestool_text01.jpg fill

output HDMI-A-1 mode 2560x1440@143.912Hz pos 1080 240
#output HDMI-A-1 bg ~/Pictures/ClearLight.jpg fill
