set $idle swayidle -w \
    timeout $idle_timeout 'light -G > /tmp/brightness && light -S 10' resume 'light -S $([ -f /tmp/brightness ] && cat /tmp/brightness || echo 100%)' \
    timeout $screen_timeout 'swaymsg "output * power off"' \
    resume 'swaymsg "output * power on"' \
    before-sleep 'playerctl pause' \
    lock $lock &
